services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb_container
    environment:
      MONGO_INITDB_DATABASE: tech_challenge_pagamentos
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-admin123}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongodb-init:/docker-entrypoint-initdb.d
    networks:
      - dev_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java_app
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATA_MONGODB_URI: mongodb://${MONGO_USER:-admin}:${MONGO_PASSWORD:-admin123}@mongodb:27017/tech_challenge_pagamentos
    ports:
      - "8080:8080"
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge

volumes:
  mongo_data:
    driver: local