services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb_container
    environment:
      MONGO_INITDB_DATABASE: techchallenge
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - dev_network

  postgres:
    image: registry.suse.com/suse/postgres:16
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dev_network

  flyway:
    image: flyway/flyway
    container_name: flyway_migration
    depends_on:
      - postgres
    entrypoint: ["flyway", "migrate"]
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      FLYWAY_USER: ${POSTGRES_USER}
      FLYWAY_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./migration:/flyway/sql
    networks:
      - dev_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java_app
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - dev_network

volumes:
  pg_data:
  mongo_data:

networks:
  dev_network: