spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USER:admin}:${MONGO_PASSWORD:admin123}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/tech_challenge_pagamentos?authSource=admin
      database: tech_challenge_pagamentos
      auto-index-creation: true
      authentication-database: admin
client:
  mercado-pago:
    user_id: 2307740945
    pos_id: 111018077
    external_store_id: "FIAP001"
    external_pos_id: "FIAP001CAIXA001"
    auth_header: "Bearer APP_USR-6626499642890434-031509-c433b0d6b17ee9c91743eded89272fde-2307740945"

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    br.com.fiap.techchallenge03: DEBUG

server:
  port: 8080

azure:
  entra-id:
    tenant-id: "12"
    tenant-name: "12"
    client-id: "12"
    client-secret: "12"