spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USER:admin}:${MONGO_PASSWORD:admin123}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/tech_challenge_pagamentos?authSource=admin
      auto-index-creation: true
      connection-pool:
        max-size: 50
        min-size: 5
        max-wait-time: 3000
        max-life-time: 0
      connect-timeout: 3000
      socket-timeout: 5000
      server-selection-timeout: 5000
      retry-writes: true
      ssl:
        enabled: false
      health:
        timeout: 3000
        enabled: true
        fail-fast: true
client:
  pedido:
    base-url: "http://localhost:8080/pedidos"
  mercado-pago:
    user_id: 123456
    pos_id: 123456
    external_store_id: "X"
    external_pos_id: "X"
    auth_header: "Bearer TEST-X"

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    br.com.fiap.techchallenge03: DEBUG

server:
  port: 8080

azure:
  entra-id:
    tenant-id: "12"
    tenant-name: "12"
    client-id: "12"
    client-secret: "12"