spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USER:admin}:${MONGO_PASSWORD:admin123}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/tech_challenge_pagamentos?authSource=admin
      database: tech_challenge_pagamentos
      auto-index-creation: true
      authentication-database: admin
client:
  mercado-pago:
    user_id: 123456
    pos_id: 123456
    external_store_id: "X"
    external_pos_id: "X"
    auth_header: "Bearer TEST-X"

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    br.com.fiap.techchallenge03: DEBUG

server:
  port: 8080

azure:
  entra-id:
    tenant-id: "12"
    tenant-name: "12"
    client-id: "12"
    client-secret: "12"