spring:
  profiles:
    active: dev
  application:
    name: techchallengeapipagamento
  data:
    mongodb:
      database: tech_challenge_pagamentos
      auto-index-creation: true
      authentication-database: admin
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operationsSorter: alpha
    docExpansion: none

tag:
  swagger:
    pagamento:
      name: "Pagamento"
      description: "API de Pagamentos"

mercado-pago:
  ativo: "${MERCADO_PAGO_ATIVO:false}"
