spring:
  profiles:
    active: dev
  application:
    name: techchallenge03
  data:
    mongodb:
      uri: mongodb://${MONGO_USER:admin}:${MONGO_PASSWORD:admin123}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/tech_challenge_pagamentos
      database: tech_challenge_pagamentos
      auto-index-creation: true
      authentication-database: admin
      connection-pool:
        max-size: 50
        min-size: 5
        max-wait-time: 3000
        max-life-time: 0
      connect-timeout: 3000
      socket-timeout: 5000
      server-selection-timeout: 5000
      retry-writes: true
      ssl:
        enabled: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operationsSorter: alpha
    docExpansion: none

tag:
  swagger:
    pagamento:
      name: "Pagamento"
      description: "API de Pagamentos"

azure:
  entra-id:
    tenant-id: "${AZURE_ENTRA_ID_TENANT_ID}"
    tenant-name: "${AZURE_ENTRA_ID_TENANT_NAME}"
    client-id: "${AZURE_ENTRA_ID_CLIENT_ID}"
    client-secret: "${AZURE_ENTRA_ID_CLIENT_SECRET}"

mercado-pago:
  ativo: "${MERCADO_PAGO_ATIVO:false}"
