apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-pagamento
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: java-app-pagamento
  template:
    metadata:
      labels:
        app: java-app-pagamento
    spec:
      containers:
        - name: java-app-pagamento
          image: alecigolini/fiap-techchallengeapipagamento:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://pagamento-dev-mongo:teste==@pagamento-dev-mongo.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@pagamento-dev-mongo@
            - name: CLIENT_MERCADO_PAGO_USER_ID
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: MP_USER_ID
            - name: CLIENT_MERCADO_PAGO_POS_ID
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: MP_POS_ID
            - name: CLIENT_MERCADO_PAGO_EXTERNAL_STORE_ID
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: MP_EXTERNAL_STORE_ID
            - name: CLIENT_MERCADO_PAGO_EXTERNAL_POS_ID
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: MP_EXTERNAL_POS_ID
            - name: CLIENT_MERCADO_PAGO_AUTH_HEADER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: MP_AUTH_HEADER
          resources:
            requests:
              cpu: "400m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1024Mi"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: java-app-pagamento
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  selector:
    app: java-app-pagamento
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: java-app-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /pagamentos
            pathType: Prefix
            backend:
              service:
                name: java-app-pagamento
                port:
                  number: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: java-app-hpa
  namespace: default
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind:  Deployment
    name: java-app-pagamento
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
        - type: Pods
          periodSeconds: 15
          value: 1
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          periodSeconds: 60
          value: 1